### ISSUE TITLE
Request: adding tags arguments when running test coverage

### ISSUE THREAD

**Issue by tempegarit** [rafaelsq/nvim-goc.lua#3]
I tested a package by running this:
`:lua require("nvim-goc").Coverage()<CR>`

It gave this error:
`panic: no such module: fts5`

It happens because I should run the test with `-tags` like this:
`$ go test -cover -tags "sqlite_fts5"`

Can you add a feature so that users can pass a `-tags` when they run the test coverage?

Thanks.

**Comment by rafaelsq** [comment]
Hi @tempegarit,
I'm sorry, I only saw your issue today (repo doesn't notify by default).
I just implemented your suggestion, just add your parameters as a list, example;
`:lua require("nvim-goc").Coverage({ "-cover", "-tags", "\"sqlite_fts5\"" })<CR>`
thanks
